#Start from GNU Compiler Collection Latest
FROM gcc:latest

#Get latest MASTER
RUN git clone https://github.com/thebsdbox/urchin.git

#Move to Urchin directory
WORKDIR "/urchin"

#Compile code, should be a makefile but meh
RUN gcc -s -Os -Wl,--discard-all -Wl,-O1 -Wall -o urchin main.c mem.c utils.c sig.c fork.c

#Use a new clean image
FROM ubuntu:latest 

#Copy Urchin to clean image
COPY --from=0 /urchin/urchin /urchin

#Set the command
CMD ["/urchin"]  
